export const products = [
  {
    productId: "10001",
    name: "Classic Comfort Fit Joggers",
    description:
      "These joggers are designed to offer ultimate comfort and style. Crafted from a soft, breathable cotton blend, they are perfect for lounging at home, running errands, or light workouts. Featuring an elastic waistband with a drawstring, tapered legs, and side pockets for convenience, these joggers provide a relaxed yet trendy fit. Pair them with your favorite t-shirt or hoodie for a laid-back look.",
    price: 300,
    onSale: true,
    salePrice: 260,
    category: "men",
    sizes: ["SM", "MD", "L", "XL"],
    stock: 10,
    image:
      "https://i.pinimg.com/736x/9b/29/7d/9b297d42bc5503a8e784025d96fe897f.jpg",
    discountPercent: 13,
    createdAt: "2025-01-06",
  },
  {
    productId: "10002",
    name: "Slim Fit Denim Jeans",
    description:
      "Elevate your wardrobe with these stylish slim-fit denim jeans. Designed to contour to your body while allowing freedom of movement, these jeans feature high-quality denim fabric that ensures durability and long-lasting color. With a classic five-pocket design and button fly, they are versatile enough for both casual outings and semi-formal occasions. Pair them with sneakers and a t-shirt for a modern look.",
    price: 500,
    onSale: false,
    salePrice: null,
    category: "women",
    sizes: ["SM", "MD", "L", "XL"],
    stock: 15,
    image:
      "https://i.pinimg.com/736x/4b/13/c4/4b13c402f0b1b35c542fff5baafd06dd.jpg",
    discountPercent: 0,
    createdAt: "2025-01-08",
  },
  {
    productId: "10003",
    name: "Cotton Crew Neck T-Shirt",
    description:
      "Stay comfortable and stylish with this premium cotton crew neck t-shirt. Made from 100% pure cotton, this t-shirt offers unmatched breathability and softness, making it ideal for daily wear. The minimalist design and versatile color make it easy to pair with jeans, shorts, or joggers. It's perfect for layering under jackets or wearing on its own for a clean, casual look.",
    price: 200,
    onSale: true,
    salePrice: 180,
    category: "men",
    sizes: ["SM", "MD", "L", "XL"],
    stock: 20,
    image:
      "https://i.pinimg.com/736x/b5/1b/d3/b51bd335ee78c257b29a4b9affb6a387.jpg",
    discountPercent: 10,
    createdAt: "2025-01-05",
  },
  {
    productId: "10004",
    name: "Leather Biker Jacket",
    description:
      "Exude confidence and style with this premium leather biker jacket. Made from high-quality leather, this jacket features a classic asymmetrical zipper design, metal hardware accents, and a comfortable inner lining. Perfect for chilly evenings or adding an edgy touch to your outfit, this jacket is a timeless addition to your wardrobe. Pair it with dark jeans and boots for a bold look.",
    price: 1500,
    onSale: false,
    salePrice: null,
    category: "men",
    sizes: ["SM", "MD", "L", "XL"],
    stock: 0,
    image:
      "https://i.pinimg.com/736x/e9/f9/5d/e9f95d57a0b683c919b7319f5d036827.jpg",
    discountPercent: 0,
    createdAt: "2025-01-07",
  },
  {
    productId: "10005",
    name: "Chino Pants",
    description:
      "A wardrobe essential, these chino pants are the perfect blend of comfort and style. Crafted from a durable cotton fabric with a slight stretch, these pants offer all-day comfort. Their sleek design makes them suitable for both formal and casual settings. Dress them up with a button-down shirt and loafers, or keep it casual with a t-shirt and sneakers.",
    price: 400,
    onSale: true,
    salePrice: 350,
    category: "men",
    sizes: ["SM", "MD", "L", "XL"],
    stock: 12,
    image:
      "https://i.pinimg.com/736x/ba/51/ce/ba51cebef5ea7a2e4e4dc4ef26c3d3be.jpg",
    discountPercent: 12.5,
    createdAt: "2025-01-09",
  },
  {
    productId: "10006",
    name: "Dangri Dress Dresses Jumpsuit shirts",
    description:
      "A versatile dangri dress made from a durable yet lightweight fabric, perfect for casual outings or chic daywear. With adjustable straps and a flattering fit, it pairs beautifully with both t-shirts and blouses.",
    price: 250,
    onSale: false,
    salePrice: null,
    category: "women",
    sizes: ["XS", "SM", "MD", "L"],
    stock: 5,
    image:
      "https://i.pinimg.com/736x/bf/12/61/bf1261040154fa4e9055b533c7d0a80d.jpg",
    discountPercent: 0,
    createdAt: "2025-01-11",
  },
  {
    productId: "10007",
    name: "F Spinola - Creative Director in Mexico, Mexico",
    description:
      "Celebrate creativity and innovation with this uniquely designed t-shirt. Inspired by the vibrant artistry of Mexico, it combines style and comfort in soft, breathable cotton. Perfect for showcasing your appreciation for design and culture, this t-shirt is a versatile addition to any wardrobe.",
    price: 150,
    onSale: true,
    salePrice: 120,
    category: "men",
    sizes: ["SM", "MD", "L", "XL"],
    stock: 22,
    image:
      "https://i.pinimg.com/736x/ca/d9/e2/cad9e2fa8a35b89112e771f9e7d5dfb3.jpg",
    discountPercent: 20,
    createdAt: "2025-01-06",
  },
  {
    productId: "10008",
    name: "Elegant Summer Dress",
    description:
      "A chic summer dress crafted from lightweight, breathable fabric, ideal for warm weather. Its elegant design and vibrant colors make it perfect for casual outings or special occasions.",
    price: 300,
    onSale: false,
    salePrice: null,
    category: "women",
    sizes: ["SM", "MD", "L"],
    stock: 15,
    image:
      "https://i.pinimg.com/736x/33/63/be/3363be6d6b1450df77a82032fafc6126.jpg",
    discountPercent: 0,
    createdAt: "2025-01-10",
  },
  {
    productId: "10009",
    name: "Men's Wool Blazer",
    description:
      "Elevate your formal wear with this sophisticated wool blazer. Made from high-quality wool, this blazer features a classic two-button design and a fitted silhouette. Perfect for business meetings, formal events, or special occasions, this blazer is a timeless addition to your wardrobe. Pair it with a dress shirt and trousers for a sharp look.",
    price: 800,
    onSale: true,
    salePrice: 680,
    category: "men",
    sizes: ["SM", "MD", "L", "XL"],
    stock: 10,
    image:
      "https://i.pinimg.com/736x/50/cb/6d/50cb6dfbf7094b3c16a057c61b921077.jpg",
    discountPercent: 15,
    createdAt: "2025-01-07",
  },
  {
    productId: "10010",
    name: "Balloon Sleeve Hem Ruffle Chiffon Shirt Top",
    description:
      "A stylish chiffon top featuring balloon sleeves and delicate ruffles at the hem, adding a feminine and elegant touch to any outfit. Perfect for casual and semi-formal occasions.",
    price: 350,
    onSale: false,
    salePrice: null,
    category: "women",
    sizes: ["6", "7", "8", "9"],
    stock: 12,
    image:
      "https://i.pinimg.com/736x/96/2c/40/962c40233d8eeb36148d690d496e8746.jpg",
    discountPercent: 0,
    createdAt: "2025-01-09",
  },
  {
    productId: "10011",
    name: "Gray Hoodie",
    description:
      "Keep your little one warm and stylish with this boys' hoodie. Made from 100% cotton, this hoodie features a comfortable fit and a fun design. Perfect for casual outings, playdates, or everyday wear, this hoodie is a great addition to your child's wardrobe. Pair it with jeans or shorts for a cool look.",
    price: 180,
    onSale: true,
    salePrice: 150,
    category: "men",
    sizes: ["MD", "L"],
    stock: 25,
    image:
      "https://i.pinimg.com/736x/ef/e5/9a/efe59ade39ef6ee1dc490d85b40ae2b4.jpg",
    discountPercent: 16.7,
    createdAt: "2025-01-08",
  },
  {
    productId: "10012",
    name: "Handmade Women's High-Waisted Green Wool Maxi Skirt - Elegant A-Line W",
    description:
      "This elegant high-waisted wool maxi skirt is the epitome of sophistication. Crafted from soft green wool, its A-line design flatters all body types. Ideal for formal gatherings and special occasions, it pairs beautifully with blouses and boots.",
    price: 200,
    onSale: false,
    salePrice: null,
    category: "women",
    sizes: ["full"],
    stock: 18,
    image:
      "https://i.pinimg.com/736x/a7/47/80/a74780cd87b07578b13a82757c69c00b.jpg",
    discountPercent: 0,
    createdAt: "2025-01-11",
  },
  {
    productId: "10013",
    name: "Red Flared Anarkali Suit Set",
    description:
      "This stunning red Anarkali suit set features intricate embroidery and a flared silhouette, making it perfect for weddings, festivals, and special occasions. Pair it with traditional jewelry for a regal look.",
    price: 1200,
    onSale: true,
    salePrice: 960,
    category: "women",
    sizes: ["SM", "MD", "L", "XL"],
    stock: 8,
    image:
      "https://i.pinimg.com/736x/7c/77/0a/7c770a30f81a6647395d291e6494861b.jpg",
    discountPercent: 20,
    createdAt: "2025-01-06",
  },
  {
    productId: "10014",
    name: "Short Sleeve Lapel Polo Shirts - Champlain Color",
    description:
      "A classic polo shirt crafted from breathable cotton, ideal for casual and semi-formal occasions. The champlain color adds a sophisticated touch to your wardrobe.",
    price: 170,
    onSale: false,
    salePrice: null,
    category: "men",
    sizes: ["SM", "MD", "L", "XL"],
    stock: 15,
    image:
      "https://i.pinimg.com/736x/04/a8/91/04a8916b97e9967fd88857f08de72d6a.jpg",
    discountPercent: 0,
    createdAt: "2025-01-10",
  },
  {
    productId: "10015",
    name: "Unavailable",
    description: null,
    price: 0,
    onSale: true,
    salePrice: 0,
    category: "boys",
    sizes: ["one size"],
    stock: 0,
    image: "(link unavailable)",
    discountPercent: 0,
    createdAt: "2025-01-07",
  },
  {
    productId: "10016",
    name: "Bell Bottom Jeans",
    description:
      "Vintage-inspired bell-bottom jeans with a modern twist. These jeans feature a flattering high-waist design and a comfortable fit, perfect for casual outings or a retro-themed look.",
    price: 180,
    onSale: true,
    salePrice: 120,
    category: "women",
    sizes: ["one size"],
    stock: 0,
    image:
      "https://i.pinimg.com/736x/63/9a/a1/639aa1f21903ef3fa9ae3337fc78abb1.jpg",
    discountPercent: 33.3,
    createdAt: "2025-01-07",
  },
  {
    productId: "10017",
    name: "Emporio Armani Trousers - Moon Rock",
    description:
      "Sophisticated and stylish, these Emporio Armani trousers in moon rock color are made from premium fabric. Perfect for formal and semi-formal occasions, they offer a sleek fit and timeless design.",
    price: 150,
    onSale: true,
    salePrice: 120,
    category: "men",
    sizes: ["SM", "MD", "L"],
    stock: 12,
    image:
      "https://i.pinimg.com/736x/ac/90/86/ac9086d088572a26f0cbbaff99ba4392.jpg",
    discountPercent: 20,
    createdAt: "2025-01-07",
  },
  {
    productId: "10018",
    name: "Classic Linen Jam Shorts - Chocolate",
    description:
      "Comfortable and airy linen shorts that are ideal for summer days or tropical vacations. The chocolate color adds a rich and stylish touch to these versatile shorts. Made from premium linen fabric, these shorts ensure breathability and comfort throughout the day. Featuring an elastic waistband and side pockets, they are as functional as they are stylish.",
    price: 50,
    onSale: true,
    salePrice: 40,
    category: "men",
    sizes: ["SM", "MD", "L"],
    stock: 20,
    image:
      "https://i.pinimg.com/736x/1b/15/96/1b1596285f9360cab6e48993b3d0d902.jpg",
    discountPercent: 20,
    createdAt: "2025-01-12",
  },
];
